### ISSUE TITLE
support for DuckDB >v0.9

### ISSUE THREAD

**Issue by Ed2uiz** [wheretrue/exon#216]
Hello again Trent,

I am running into the following error on DuckDB v0.9 and v0.9.1. Any advice on how to address?

```
❯ duckdb -unsigned
v0.9.1 401c8061c6
Enter ".help" for usage hints.
D SET custom_extension_repository='dbe.wheretrue.com/exon/latest';
D INSTALL exon;
Error: IO Error: Failed to copy local extension "exon" at PATH "dbe.wheretrue.com/exon/latest/v0.9.1/osx_arm64/exon.duckdb_extension"
```

Thanks for creating this excellent repo!

**Comment by tshauck** [comment]
Hey Eddy, thanks for filing the issue. There've been some build changes related to extensions in duckdb 0.9+, so please give me a few days to work through things, and I'll follow up on this issue once I've got it ready.

**Comment by tshauck** [comment]
Hey @Ed2uiz, I hate to do this, but I think I'm actually going to deprecate exon-duckdb. I'm not sure the additional complexity of maintaining it is worth it, when someone could use [biobear from python w/ duckdb](https://github.com/wheretrue/biobear#using-duckdb) or soon `exonR`. I think you were mostly an R user, and if so, happy to ping you when that rolls out in the next week.

**Comment by Ed2uiz** [comment]
makes sense. look forward to testing out exonR. thanks!

**Comment by tshauck** [comment]
Cool, thanks for understanding! Just got things working e2e for what I described, so should just be another day or two, then a release'll be out. Will follow up here when that's ready.

**Comment by tshauck** [comment]
@Ed2uiz, I think this should be usable now. There's a quick example here: https://wheretrue.r-universe.dev/exonr/doc/manual.html#ExonDataFrame, but please let me know if anything could be improved.

There are some build issues depending on which platform you're using, so obv please let me know if you run into any blockers w/ install and I'll work through them. ([install][], [issue][]).

Thanks!

[install]: https://wheretrue.r-universe.dev/exonr
[issue]: https://github.com/r-universe/workflows/issues/1
