### ISSUE TITLE
fastest way to subset bam/sam by tags

### ISSUE THREAD

**Issue by Ed2uiz** [wheretrue/exon#493]
Hey Trent! 

I've started working on some sequence analysis again and I'm wondering what's the fastest way to subset/parse a large bam file by a specific tag using exon?

My use case:
I'm specifically trying to subset a 60GB .bam file by a list of cell barcode ids mapping to the 'CB:Z' tag. I used the option `SET exon.bam_parse_tags = true;` to infer a struct for the tags. I believe I can query the tags using `exon_session$sql(<some sql to parse cb column>)`. It also seems possible to convert the `ExonDataFrame` into an arrow table and then write that to DuckDB for filtering, but I've noticed this requires the entire arrow table to fit into memory. I'm wondering if there's a good alternative method to do the arrow conversion in chunks or batches.

```
exon_session = ExonRSessionContext$new()
exon_session$sql("SET exon.bam_parse_tags = true;")
bam = exon_session$sql("CREATE EXTERNAL TABLE bam STORED AS BAM LOCATION '/path/to/my.bam'")
bam_small = exon_session$sql("SELECT * FROM bam limit 5")

# convert to duckdb via arrow
con = DBI::dbConnect(duckdb::duckdb(), "test-bam.db")
bam_small_arrow = bam_small$to_arrow() # this can be slow and seems to require the entire arrow table to fit into memory. is it possible to skip this step or do it in batches? 
arrow::to_duckdb(
   bam_small_arrow,
   con = con,
   table_name = "bam_small",
   auto_disconnect = F
) |> dplyr::compute(name = "bam_small", temporary = F)

dplyr::tbl(con, dplyr::sql("select * from bam_small where tags.cb = 'AAACCCAAGATGCAGC-1';") # duckdb can filter the struct just fine

```

**Comment by tshauck** [comment]
Thanks for all the info... could you try `tags."CB"`? I think there's slightly different semantics between duckdb and Apache DataFusion (what exon uses under the hood) for struct accessing w.r.t. case sensitivity.

```
❯ SET exon.sam_parse_tags = true;
0 rows in set. Query took 0.001 seconds.

❯ SELECT tags.rg FROM sam_scan('exon/exon-core/test-data/datasources/sam/test.sam') LIMIT 5;
Error during planning: Field rg not found in struct
❯ SELECT tags."RG" FROM sam_scan('exon/exon-core/test-data/datasources/sam/test.sam') LIMIT 5;
+--------------------+
| tmp_table.tags[RG] |
+--------------------+
| grp1               |
+--------------------+
1 row in set. Query took 0.030 seconds.
```

Test sam:

```
head exon/exon-core/test-data/datasources/sam/test.sam
@HD     VN:1.4  SO:queryname
@CO     The MIT License
@SQ     SN:ref1 LN:56   M5:08c04d512d4797d9ba2a156c1daba468
ref1_grp1_p001  99      ref1    1       0       10M     =       25      34      CGAGCTCGGT      !!!!!!!!!!      MD:Z:10 NM:i:0  RG:Z:grp1       BC:Z:ACGT       H0:i:1  aa:A:!  ab:A:~  fa:f:3.14159    za:Z:Hello world!       ha:H:DEADBEEF   ba:B:c,-128,0,127       bb:B:C,0,127,255        bc:B:s,-32768,0,32767    bd:B:S,0,32768,65535    be:B:i,-2147483648,0,2147483647 bf:B:I,0,2147483648,4294967295  bg:B:f,2.71828,6.626e-34,2.9979e+09
```

Hope that works, but please lmk if not.

**Comment by Ed2uiz** [comment]
Thanks! That seemed to do the trick. It seems like I need to escape the quotation marks in R. 

```
> tags_cb = exon_session$sql("SELECT tags.\"CB\" FROM bam_scan('/path/to/my.bam') LIMIT 5;")
> tags_cb$to_arrow() |> dplyr::as_tibble()
# A tibble: 5 × 1
  `tmp_table.tags[CB]`
  <chr>               
1 ACATGCACATCGGAAG-1  
2 CCTCAACTCACCCTCA-1  
3 ACGTACACATGGAACG-1  
4 TGAGGAGTCAAACTGC-1  
5 ATTACCTGTACTAGCT-1  
```

If you prefer, feel free to close this issue and I can make a new one for the arrow stream feature request.

**Comment by tshauck** [comment]
Ok great, I'll close this issue. For the streaming issue, I went ahead and made #497. Please comment if it doesn't match what you hope to happen. Otherwise, I think (hope) it'll be reasonably straightforward, I just probably won't get the chance to make a release until the weekend.
