### ISSUE TITLE
Expose `RecordBatchStreamReader` via R API

### ISSUE THREAD

**Issue by tshauck** [wheretrue/exon#497]
Currently via the SQL interface in R, you can get the arrow table, but that materializes the table in memory.

This work, then, would be to expose the `RecordBatchStreamReader` so it could be passed to other arrow-compatible tools (e.g. duckdb, see https://github.com/wheretrue/exon/issues/493) in a streaming fashion.

See https://github.com/wheretrue/exon/blob/62eeea15fab8d7ada0000c714a1c4c324787bb1a/exon-r/exonr/R/main.R#L198.

**Comment by tshauck** [comment]
@Ed2uiz, would you mind trying this on your end at your convenience? For an example see: https://github.com/wheretrue/exon/blob/e18397f549201c6f0e003fce51cbc3c95519a5f9/exon-r/exonr/tests/testthat/test_read.R#L140-L155

Note the `to_record_batch_reader` as the method to call.

**Comment by Ed2uiz** [comment]
works great, thanks!

**Comment by tshauck** [comment]
Awesome, thanks for reporting the issue!
